# Generated by Django 4.2.2 on 2023-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_school__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolment',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
